sudo: false
language: node_js
node_js:
  - node

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - nvm install 8
  - nvm use 8
  - npm install node-pre-gyp
  # - npm i --no-optional
  # - npm dedupe
  # - npm up
  - npm install -g vsce

install:
  - npm install
  - vsce package

script:
  - npm run lint
  - npm run test
